<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>MISAT</Title>
    <PackageProjectUrl>https://ricardomiss.github.io/MISAT/</PackageProjectUrl>
    <Description>Librería para uso de los servicios del SAT</Description>
    <PackAsTool>False</PackAsTool>
    <VersionPrefix>1.5.0</VersionPrefix>
    <Authors>Ricardo Miss</Authors>
    <RepositoryUrl>https://github.com/ricardomiss/MISAT</RepositoryUrl>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <PackageTags>SAT; WebService; CFDI; </PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.1" />
  </ItemGroup>
  
</Project>
